language: node_js

node_js:
  - "8"

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - ./node_modules/

before_install:
  - export TRAVIS_SOURCE_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - if [ "$TRAVIS_SOURCE_BRANCH" = "master" ]; then openssl aes-256-cbc -K $encrypted_72bd71d55297_key -d -in ./.env.production.enc -iv $encrypted_72bd71d55297_iv -out ./.env.production; fi

before_script:
  - if [ "$TRAVIS_SOURCE_BRANCH" = "master" ]; then
      curl --location https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
      chmod +x ./cc-test-reporter;
      ./cc-test-reporter before-build;
    fi

script:
  - yarn run lint
  - yarn run test
  - if [ "$TRAVIS_SOURCE_BRANCH" = "master" ]; then yarn run build; fi

deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  provider: pages
  skip-cleanup: true
  on:
    branch: master

after_script:
  - if [ "$TRAVIS_SOURCE_BRANCH" = "master" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

notifications:
  email:
    on_failure: change
